=== anzhiruodu/springboot/jaxbTest/target/classes/world.xsd
<?xml version="1.0"  encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <xs:element name="world">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="people" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="testplmn"  minOccurs="1" maxOccurs="1" />
                <xs:element name="plant" type="xs:string"/>
                <xs:element name="Inanimate_body" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="desc" default="描述世界万物"/>
        </xs:complexType>

    </xs:element>
    <xs:element name="people">
        <xs:simpleType>
            <xs:restriction base="xs:string"><!-- 限定（restriction）用于为 XML 元素或者属性定义可接受的值  base="xs:string"必须写成string-->
                <xs:enumeration value="男" />
                <xs:enumeration value="女"/>
                <xs:enumeration value="人妖"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    
    <xs:element name="testplmn">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="testset"></xs:element>
                <xs:element name="testset2"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="testset">
        <xs:complexType>
            <xs:sequence>
            <!--您必须在 group 声明内部定义一个 all、choice 或者 sequence 元素-->
                 <xs:group ref="testcase"></xs:group>
                 <xs:element name="testcase1" type="xs:string" ></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="testcase">
        <xs:sequence>
            <xs:element name="test1" type="xs:string"></xs:element>
            <xs:element name="test2" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:group>
</xs:schema>

=== anzhiruodu/springboot/jaxbTest/src/main/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<world  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="world.xsd">

    <people>人妖</people>
    <testplmn>
        <test1>test1</test1>
        <test2>test2</test2>
        <testcase1>testcase1</testcase1>

        <test1>test1</test1>
        <test2>test2</test2>
        <testcase1>testcase1</testcase1>

        <testset2>testcase2</testset2>
    </testplmn>
    <plant>glass</plant>
    <Inanimate_body></Inanimate_body>


</world>

=== anzhiruodu/springboot/jaxbTest/target/classes/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<world  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="world.xsd">

    <people>人妖</people>
    <testplmn>
        <testset>
            <test1> test11</test1>
            <test2>test22</test2>
            <testcase1>testcase1</testcase1>
        </testset>
        <testset2>testset2</testset2>
    </testplmn>
    <plant>glass</plant>
    <Inanimate_body></Inanimate_body>


</world>
